name: CodeCov Coverage Uploader

on:
  push:
    branches:
      - testcov

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build micro integrator with Maven
        continue-on-error: true
        run: mvn -B clean install --file pom.xml -fae
